#!/bin/bash

RUST_BINARY_PATH="rust-examples/build/"
OLD_RUST_EXAMPLE_PATH="old_rust_example/"
files=$(ls $RUST_BINARY_PATH)
invalid_file_type=".txt"
except_list="fibonacci date"
for filename in $files
do
    if [[ $filename != *$invalid_file_type && !($except_list =~ $filename) ]]
    then
        #echo $filename
        objdump -d ${RUST_BINARY_PATH}${filename} > ${RUST_BINARY_PATH}${filename}$invalid_file_type
    fi
done
objdump -d ${OLD_RUST_EXAMPLE_PATH}hello > ${OLD_RUST_EXAMPLE_PATH}hello$invalid_file_type
objdump -d ${OLD_RUST_EXAMPLE_PATH}minimal_hook > ${OLD_RUST_EXAMPLE_PATH}minimal_hook$invalid_file_type